src/Controllers/CompaniesController.cs
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ContosoCrafts.WebSite.Controllers
{
    /// <summary>
    /// Companies controller is used to control the CRUDi actions to be performed for companies.
    /// </summary>
    public class CompaniesController : Controller
    {
        /// <summary>
        /// Constructor for Companiescontroller
        /// </summary>
        /// <param name="companyService"></param>
        public CompaniesController(JsonFileCompanyService companyService)
        {
            CompanyService = companyService;
        }

        // Getter for CompanyService
        public JsonFileCompanyService CompanyService { get; }

        /// <summary>
        /// GetAllData method is used to Get the list of all the companies, it parses the JSON file and converts into company model list
        /// </summary>
        /// <returns>List of Company Model</returns>
        [HttpGet]
        public IEnumerable<CompanyModel> Get()
        {
            return CompanyService.GetAllData();
        }
    }
}

src/Pages/Companies/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;

namespace ContosoCrafts.WebSite.Pages.Companies
{
    /// <summary>
    /// Create Page
    /// </summary>
    public class CreateModel : PageModel
    {
        // Data middle tier
        public JsonFileCompanyService CompanyService { get; }

        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public CreateModel(JsonFileCompanyService companyService)
        {
            CompanyService = companyService;
        }

        // The data to show
        public CompanyModel Company;

        /// <summary>
        /// REST Get request
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet()
        {
            Company = CompanyService.CreateData();

            // Redirect the webpage to the Update page populated with the data so the user can fill in the fields
            return RedirectToPage("./Update", new { Id = Company.Id });
        }
    }
}

src/Pages/Companies/Delete.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
namespace ContosoCrafts.WebSite.Pages.Companies
{

    /// <summary>
    /// Manage the Delete of the data for a single record
    /// </summary>
    public class DeleteModel : PageModel
    {

        // Data middletier
        public JsonFileCompanyService CompanyService { get; }

        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public DeleteModel(JsonFileCompanyService companyService)
        {
            CompanyService = companyService;
        }

        // The data to show, bind to it for the post
        [BindProperty]
        public CompanyModel Company { get; set; }

        /// <summary>
        /// REST Get request
        /// Loads the Data
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet(string id)
        {
            Company = CompanyService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));
            if(Company == null)
            {
                return RedirectToPage("./Index");
            }
            return Page();
        }

        /// <summary>
        /// Post the model back to the page
        /// The model is in the class variable Product
        /// Call the data layer to Delete that data
        /// Then return to the index page
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            var company = CompanyService.DeleteData(Company.Id);

            return RedirectToPage("./Index");
        }

    }

}

src/Pages/Companies/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace ContosoCrafts.WebSite.Pages.Companies
{
    /// <summary>
    /// Index Page will return all the data to show
    /// </summary>
    public class IndexModel : PageModel
    {
        /// <summary>
        /// Default Constructor
        /// </summary>
        /// <param name="companyService"></param>

        public IndexModel(JsonFileCompanyService companyService)
        {
            CompanyService = companyService;
        }

        // Data Service
        public JsonFileCompanyService CompanyService { get; }

        // Collection of the Data
        public IEnumerable<CompanyModel> Companies { get; private set; }
        [BindProperty(SupportsGet = true)]
        [RegularExpression(@"^[a-z A-Z 0-9]+$", ErrorMessage = "Please enter a valid company name")]

        //public IEnumerable<CompanyModel> CompaniesList { get; private set; }

        //Getter and setter to Search string
        public string Search { get; set; }
        public string Sort { get; set; }

        /// <summary>
        /// REST OnGet, return all data
        /// </summary>
        public void OnGet()
        {
            Companies = CompanyService.SearchCompany(Search);
        }

        /// <summary>
        /// REST OnPost, sort all data in ascending order
        /// </summary>
        public void OnPostSortAsc(string SortOrder)
        {
            Companies = CompanyService.SortCompany("ASC");
        }

        /// <summary>
        /// REST OnPost, sort all data in descending order
        /// </summary>
        public void OnPostSortDesc(string SortOrder)
        {
            Companies = CompanyService.SortCompany("DESC");
        }
    }
}

src/Pages/Companies/Read.cshtml.cs
using System.Linq;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoCrafts.WebSite.Pages.Companies
{
    /// <summary>
    /// Read page will read the data related to particular company
    /// </summary>
    public class ReadModel : PageModel
    {
        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="companyService"></param>
        public ReadModel(JsonFileCompanyService companyService)
        {
            CompanyService = companyService;
        }

        // Data to show
        public CompanyModel Company { get; set; }

        // Data middletier
        public JsonFileCompanyService CompanyService { get; set; }

        /// <summary>
        /// REST Get request
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet(string id)
        {
            Company = CompanyService.GetAllData().FirstOrDefault(x => x.Id == id);
            if (Company == null)
            {
                return RedirectToPage("./Index");
            }

            return Page();
        }
    }
}

src/Pages/Companies/Update.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;

namespace ContosoCrafts.WebSite.Pages.Companies
{
    /// <summary>
    /// Manage the Update of the data for a single record
    /// </summary>
    public class UpdateModel : PageModel
    {
        // Data middletier
        public JsonFileCompanyService CompanyService { get; }

        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public UpdateModel(JsonFileCompanyService companyService)
        {
            CompanyService = companyService;
        }

        // The data to show, bind to it for the post
        [BindProperty]
        public CompanyModel Company { get; set; }

        /// <summary>
        /// REST Get request
        /// Loads the Data
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet(string id)
        {
            Company = CompanyService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));
            if (Company == null)
            {
                return RedirectToPage("./Index");
            }
            return Page();
        }

        /// <summary>
        /// Post the model back to the page
        /// The model is in the class variable Product
        /// Call the data layer to Update that data
        /// It also checks the duplicate company and doesnt allow user to add duplicate company name
        /// Then return to the index page
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var companies = CompanyService.GetAllData();
            var companyRequired = companies.Where(a => a.Name == Company.Name && a.JobRoleName == Company.JobRoleName)
                        .Select(b => b)
                        .FirstOrDefault();
            if (companyRequired != null && companyRequired.H1BSupport == Company.H1BSupport)
            {
                CompanyService.DeleteData(Company.Id);
                return RedirectToPage("./Index");
            }
            CompanyService.UpdateData(Company);

            return RedirectToPage("./Index");
        }
    }
}

src/Pages/Product/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;

namespace ContosoCrafts.WebSite.Pages.Product
{
    /// <summary>
    /// Create Page
    /// </summary>
    public class CreateModel : PageModel
    {
        /// <summary>
        /// Data Middle tier (services)
        /// </summary>
        public JsonFileProductService ProductService { get; }

        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public CreateModel(JsonFileProductService productService)
        {
            ProductService = productService;
        }

        /// <summary>
        /// The data to show
        /// </summary>
        public ProductModel Product;

        /// <summary>
        /// REST Get request
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet()
        {
            Product = ProductService.CreateData();
         
            // Redirect the webpage to the Update page populated with the data so the user can fill in the fields
            return RedirectToPage("./Update", new { Id = Product.Id });
        }
    }
}

src/Pages/Product/Delete.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;

namespace ContosoCrafts.WebSite.Pages.Product
{
    /// <summary>
    /// Manage the Delete of the data for a single record
    /// </summary>
    public class DeleteModel : PageModel
    {
        /// <summary>
        /// Data Middle tier (services)
        /// </summary>
        public JsonFileProductService ProductService { get; }

        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public DeleteModel(JsonFileProductService productService)
        {
            ProductService = productService;
        }

        // The data to show, bind to it for the post
        [BindProperty]
        public ProductModel Product { get; set; }

        /// <summary>
        /// REST Get request
        /// Loads the Data
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet(string id)
        {
            Product  = ProductService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));
            if (Product == null)
            {
                return RedirectToPage("./Index");
            }
            return Page();
        }

        /// <summary>
        /// Post the model back to the page
        /// The model is in the class variable Product
        /// Call the data layer to Delete that data
        /// Then return to the index page
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ProductService.DeleteData(Product.Id);

            return RedirectToPage("./Index");
        }
    }
}

src/Pages/Product/Read.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;

namespace ContosoCrafts.WebSite.Pages.Product
{
    /// <summary>
    /// Read page to display information related to particular product
    /// </summary>
    public class ReadModel : PageModel
    {
        /// <summary>
        /// Data Middle tier (services)
        /// </summary>
        public JsonFileProductService ProductService { get; }

        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public ReadModel(JsonFileProductService productService)
        {
            ProductService = productService;
        }

        // The data to show
        public ProductModel Product;

        /// <summary>
        /// REST Get request
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet(string id)
        {
            Product  = ProductService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));
            if (Product == null)
            {
                return RedirectToPage("./Index");
            }
            return Page();
        }
    }
}

src/Pages/Product/Update.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;

namespace ContosoCrafts.WebSite.Pages.Product
{
    /// <summary>
    /// Manage the Update of the data for a single record
    /// </summary>
    public class UpdateModel : PageModel
    {
        /// <summary>
        /// Data Middle tier (services)
        /// </summary>
        public JsonFileProductService ProductService { get; }

        /// <summary>
        /// Defualt Construtor
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public UpdateModel(JsonFileProductService productService)
        {
            ProductService = productService;
        }

        // The data to show, bind to it for the post
        [BindProperty]
        public ProductModel Product { get; set; }

        /// <summary>
        /// REST Get request
        /// Loads the Data
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet(string id)
        {
            Product  = ProductService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));
            if (Product == null)
            {
                return RedirectToPage("./Index");
            }
            return Page();
        }

        /// <summary>
        /// Post the model back to the page
        /// The model is in the class variable Product
        /// Call the data layer to Update that data
        /// Then return to the index page
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ProductService.UpdateData(Product);

            return RedirectToPage("./Index");
        }
    }
}

src/Pages/Companies/Create.cshtml
@page
@using ContosoCrafts.WebSite.Services
@inject JsonFileProductService CompanyService
@model ContosoCrafts.WebSite.Pages.Companies.CreateModel

@{
    ViewData["Title"] = "Create page";
}

src/Pages/Companies/Delete.cshtml
@page "{id}"
@using ContosoCrafts.WebSite.Services
@inject JsonFileCompanyService CompanyService
@model ContosoCrafts.WebSite.Pages.Companies.DeleteModel

@{
    ViewData["Title"] = "Delete page";
}

<h1>Delete</h1>

<div class="container">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @Html.HiddenFor(x => x.Company.Id)

        <div class="form-group">
            <label asp-for="Company.Name" class="control-label"></label>
            <input asp-for="Company.Name" class="form-control" disabled/>
        </div>

        <div class="form-group">
            <label asp-for="Company.H1BSupport" class="control-label"></label>
            <input asp-for="Company.H1BSupport" class="form-control" disabled/>
        </div>

        <div class="form-group">
            <label asp-for="Company.JobRoleName" class="control-label"></label>
            <input asp-for="Company.JobRoleName" class="form-control" disabled/>
        </div>

        <h1>Confirm Delete of this item</h1>

        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-primary" />
        </div>
    </form>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Pages/Companies/Index.cshtml
@page "/Companies/Index"
@model ContosoCrafts.WebSite.Pages.Companies.IndexModel
@{
    ViewData["Title"] = "Index page";
}

<div class="container">
    <br />
    <form method="get">
        <div class="input-group">
            <input class="form-control" asp-for="Search" />
            <div class="input-group-append">
                <button type="submit" class=" btn btn-primary">Search</button>
            </div>
        </div>
        <span asp-validation-for="Search" class="text-danger"></span>
    </form>
    <br />
    <br />
    <table>
        <a asp-page="create" class="btn-link">Add company</a>
        <br>
        
    </table>
    <br>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    <table class="comapanyNameField">
                        <th>
                            Name
                        </th>
                        <th>
                            <form asp-page-handler="sortAsc" method="post">
                                <button id="down-button" type="submit"></button>
                            </form>
                        </th>
                        <th>
                            <form asp-page-handler="sortDesc" method="post">
                                <button id="up-button" type="submit"></button>
                            </form>
                        </th>
                    </table></th>
                <th>H1B Support</th>
                <th>Job Role</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var company in Model.Companies)
            {
                <tr>
                    <td>@company.Name</td>
                    <td>@company.H1BSupport</td>
                    <td>@company.JobRoleName</td>
                    <td><a asp-page="Read" asp-route-id="@company.Id" class="btn btn-primary">Read</a> </td>
                    <td><a asp-page="Update" asp-route-id="@company.Id" class="btn btn-primary">Update</a> </td>
                    <td><a asp-page="Delete" asp-route-id="@company.Id" class="btn btn-danger">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/Pages/Companies/Read.cshtml
@page "{id}"
@using ContosoCrafts.WebSite.Services
@inject JsonFileCompanyService CompanyService
@model ContosoCrafts.WebSite.Pages.Companies.ReadModel

@{
    ViewData["Title"] = "Read page";
}

<h1>@Model.Company.Name</h1>

<div class="container">
    <table class="table table-bordered table-striped">
        <tr>
            <th>Job Role Name</th>
            <th>H1B Support</th>
        </tr>
        <tr>
            <td class="title" id="companyId">@Model.Company.JobRoleName</td>
            <td class="title" id="companyId">@Model.Company.H1BSupport</td>
        </tr>
    </table>
</div>

<br />
<br />

<div class="row">
    <a asp-page="Update" asp-route-id="@Model.Company.Id" class="btn btn-primary">Update</a> &nbsp; &nbsp;
    <a asp-page="Delete" asp-route-id="@Model.Company.Id" class="btn btn-danger">Delete</a>
</div>

src/Pages/Companies/Update.cshtml
@page "{id}"
@using ContosoCrafts.WebSite.Services
@inject JsonFileCompanyService CompanyService
@model ContosoCrafts.WebSite.Pages.Companies.UpdateModel

@{
    ViewData["Title"] = "Update page";
}
@if (string.IsNullOrEmpty(Model.Company.Name))
{
    <h1>Create</h1>
}
else
{
    <h1>Update</h1>
}

<div class="container">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @Html.HiddenFor(x => x.Company.Id)


        <div class="form-group">
            <label asp-for="Company.Name" class="control-label"></label>
            <input asp-for="Company.Name" class="form-control" />
            <span asp-validation-for="Company.Name" class="text-danger"></span>
        </div>



        <div class="form-group">
            <label asp-for="Company.H1BSupport" class="control-label"></label>
            <select name="Company.H1BSupport" class="form-control">
                <option value="True">True</option>
                <option value="False">False</option>
            </select>
        </div>

        <div class="form-group">
            <label asp-for="Company.JobRoleName" class="control-label"></label>
            <input asp-for="Company.JobRoleName" class="form-control" />
            <span asp-validation-for="Company.JobRoleName" class="text-danger"></span>
        </div>


        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}